version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - gocyclo
    - gosec
    - misspell
    - revive
    - unused
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: _test\.go
      - path: _test\.go
        text: declaration of "(err|ctx)" shadows declaration at
      - path: (.+)\.go$
        text: "^unused-parameter: "
      - linters:
          - revive
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
    paths:
      - third_party$
      - builtin$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fido-device-onboard/go-fdo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
