version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - gocyclo
    - gosec
    - misspell
    - revive
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
      - path: (.+)\.go$
        text: '^unused-parameter: '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fido-device-onboard/go-fdo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
